apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-i3bx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-i3bx@sha256:c2281466ee8624d7713cd27a92f98d7d6630825f4233599fde5c17e51eb0c2d2
        name: my-nodejs
        resources: {}
status: {}
